
#define DEFAULT_AMBIENT_ENVIRONMENT_DAY list(\
	'stalker/sound/ambience/rnd_outdoor/ambient_bird_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_bird_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_dog_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_drone_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_11.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_12.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_13.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_14.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_15.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_16.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_17.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_gunfire_18.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_mutant_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_mutant_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_wind_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_wind_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_wind_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/ambient_wind_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_explosion_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_explosion_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun1_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun1_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun1_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun1_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun1_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun2_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun2_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun2_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun2_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun2_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun3_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun3_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun3_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun3_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/dist_gun3_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/heavy_wind_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/heavy_wind_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/heavy_wind_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/heavy_wind_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/night_scream_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/night_scream_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/night_scream_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_bird_11.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_boar_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_boar_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_boar_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_boar_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_cricket_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_cricket_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_11.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_12.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_13.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_14.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_crow_15.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dark_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_dog10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_drone_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_drone_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_growl_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_growl_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_helicopter.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_helicopter_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_horror_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_horror_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_insect_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_11.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_12.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_13.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_mutant_14.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_raven_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_raven_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_raven_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_raven_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_5.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_6.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_7.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_8.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_9.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_10.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_11.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_12.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_13.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_14.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_15.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_16.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_17.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_18.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_shooting_19.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_wind_1.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_wind_2.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_wind_3.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_wind_4.ogg',\
	'stalker/sound/ambience/rnd_outdoor/rnd_wind_tree.ogg'\
	)
