
#define DEFAULT_AMBIENT_ENVIRONMENT_UNDERGROUND list(\
	'stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_1.ogg','stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_2.ogg',\
	'stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_3.ogg','stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_4.ogg',\
	'stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_5.ogg','stalker/sound/ambience/ugrnd/rnd_ugrnd_amb_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_7.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_banging_7.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_machine_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_machine_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_machine_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_ambient_machine_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_ambient_machine_5.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_drip_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_drip_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_drip_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_7.ogg','stalker/sound/ambience/ugrnd/ugrnd_drip_8.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_9.ogg','stalker/sound/ambience/ugrnd/ugrnd_drip_10.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drip_11.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drone_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_drone_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_drone_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_drone_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_lab_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_lab_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_lab_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_lab_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_lab_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_lab_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_metal_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_metal_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_metal_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_metal_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_metal_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_metal_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_metal_7.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_4.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_5.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_6.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_7.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_8.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_9.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_10.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_noise_11.ogg','stalker/sound/ambience/ugrnd/ugrnd_noise_12.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_whispers_1.ogg','stalker/sound/ambience/ugrnd/ugrnd_whispers_2.ogg',\
	'stalker/sound/ambience/ugrnd/ugrnd_whispers_3.ogg','stalker/sound/ambience/ugrnd/ugrnd_whispers_4.ogg',\
	)
