//#define LOWMEMORYMODE
#include "map_files/ZonaRemastered/backwater.dmm"
#include "map_files/ZonaRemastered/under.dmm"
#include "map_files/ZonaRemastered/kordon.dmm"
#include "map_files/ZonaRemastered/bar.dmm"
#include "map_files/ZonaRemastered/agroprom.dmm"
#include "map_files/ZonaRemastered/svalka.dmm"
#include "map_files/ZonaRemastered/radar.dmm"
#include "map_files/ZonaRemastered/Yantar.dmm"
#include "map_files/ZonaRemastered/ArmyWarehouses.dmm"
#include "map_files/ZonaRemastered/greatswamps.dmm"
#include "map_files/ZonaRemastered/DeadCity.dmm"
#include "map_files/ZonaRemastered/DarkDolina.dmm"
#include "map_files/ZonaRemastered/WildTerritory.dmm"

#define FORCE_MAP "_maps/zonaremastered.json"
