/mob/living/proc/add_whitelist_items()
    if (check_st_whitelist(src.ckey, "vipcard"))
        var/obj/item/vipcard/O = new()
        spawn(300)
            src.equip_to_slot(O, SLOT_IN_BACKPACK)
            to_chat(src, "Ах, да. Вы же припрятали [O.name] у себя в сумке.")
